# Generated by Django 3.2 on 2022-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='address',
            field=models.CharField(max_length=30, verbose_name='адрес места'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='launch_geocoder_date',
            field=models.DateTimeField(unique=True, verbose_name='Дата запроса к геокодеру'),
        ),
    ]
