# Generated by Django 3.2 on 2022-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_auto_20220202_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='address',
            field=models.CharField(max_length=30, unique=True, verbose_name='адрес места'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
