# Generated by Django 3.2 on 2022-01-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20220111_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Адрес доставки'),
        ),
    ]
