# Generated by Django 3.2 on 2022-01-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_rename_phone_number_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('processed', 'Обработанный заказ'), ('unprocessed', 'Не обработанный заказ')], default='unprocessed', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
