# Generated by Django 3.2 on 2022-01-16 15:14

from django.db import migrations




def save_price_old_orders(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    for order_product in OrderProduct.objects.select_related('product').iterator():
        order_product.fixed_price = order_product.product.price
        order_product.save()



class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_orderproduct_fixed_price'),
    ]

    operations = [
        migrations.RunPython(save_price_old_orders)
    ]
