# Generated by Django 3.2 on 2022-01-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20220116_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('processed', 'Обработанный заказ'), ('unprocessed', 'Не обработанный заказ')], db_index=True, default='unprocessed', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
