# Generated by Django 3.2 on 2022-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20220126_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('cashless', 'Электронно'), ('not_selected', 'Не выбранно')], db_index=True, default='not_selected', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
