# Generated by Django 3.2 on 2022-02-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenuitem',
            name='order',
        ),
    ]
