# Generated by Django 3.2 on 2022-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_remove_restaurantmenuitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
