# Generated by Django 3.2 on 2022-02-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20220204_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='name',
            new_name='order',
        ),
    ]
